apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: rhtas-fbc
spec:
  project: rhtas-fbc
  template:
    name: rhtas-fbc-project-template
    values:
      - name: version
        value: "v1.4"
      - name: operator
        value: "rhtas-operator"
      - name: gitRevision
        value: "main"
