apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1-0

resources:
  - ../../base/operator

patches:
  - path: patch.yaml
    target:
      name: operator
      kind: ProjectDevelopmentStream


