apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: model-validation-operator-e2e-
spec:
  workspaces:
    - name: work
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  pipelineSpec:
    params:
      - name: SNAPSHOT
      - name: OCP_VERSION
        default: "4.19"
      - name: MODEL_VALIDATION_OPERATOR_NS
        default: model-validation-operator-system
      - name: MODEL_VALIDATION_OPERATOR_E2E_NS
        default: e2e-webhook-test-ns
      - name: MODEL_VALIDATION_OPERATOR_GIT_URL
        default: https://github.com/securesign/model-validation-operator
      - name: MODEL_VALIDATION_TEST_IMAGE
        default: ttl.sh/model-validation-test-model:1.0.0
      - name: MODEL_TRANSPARENCY_IMG
        default: quay.io/securesign/model-transparency@sha256:6db7fa2b956875a6f507811166b47b164d463dea78ab4403c6d7648d838b8acb
    workspaces:
      - name: work
    tasks:
      - name: parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/konflux-ci/tekton-integration-catalog
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/test-metadata/0.3/test-metadata.yaml
        params:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
      - name: provision-eaas-space
        taskRef:
          resolver: bundles
          params:
            - name: name
              value: eaas-provision-space
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1-4e4fa7355a6a51083954408e7e3b647e3bddb8d8
            - name: kind
              value: task
        params:
          - name: ownerName
            value: $(context.pipelineRun.name)
          - name: ownerUid
            value: $(context.pipelineRun.uid)
      - name: provision-cluster
        runAfter:
          - provision-eaas-space
        taskSpec:
          results:
            - name: clusterName
              value: "$(steps.create-cluster.results.clusterName)"
          steps:
            - name: pick-version
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
              params:
                - name: prefix
                  value: "$(params.OCP_VERSION)"
            - name: create-cluster
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: version
                  value: "$(steps.pick-version.results.version)"
                - name: instanceType
                  value: m5.large
                - name: timeout
                  value: 60m
                - name: imageContentSources
                  value: |
                    - source: registry.redhat.io/rhtas/model-validation-operator-bundle
                      mirrors:
                        - quay.io/securesign/model-validation-operator-bundle
                    - source: registry.redhat.io/rhtas/model-validation-operator
                      mirrors:
                        - quay.io/securesign/model-validation-operator
                    - source: registry.redhat.io/rhtas/model-validation-rhel9-operator
                      mirrors:
                        - quay.io/securesign/model-validation-operator
      - name: clone-operator-source-code
        runAfter:
          - parse-metadata
          - provision-eaas-space
          - provision-cluster
        taskRef:
          params:
            - name: name
              value: git-clone
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1
            - name: kind
              value: task
          resolver: bundles
        params:
          - name: url
            value: $(tasks.parse-metadata.results.git-url)
          - name: revision
            value: $(tasks.parse-metadata.results.git-revision)
          - name: subdirectory
            value: "operator"
        workspaces:
          - name: output
            workspace: work
        when:
          - input: "$(tasks.parse-metadata.results.component-name)"
            operator: in
            values: [ "model-validation-operator", "model-validation-operator-bundle" ]
      - name: prepare-env
        runAfter:
          - clone-operator-source-code
        workspaces:
          - name: source-code
            workspace: work
        taskSpec:
          volumes:
            - name: credentials
              emptyDir: { }
          workspaces:
            - name: source-code
          steps:
            - name: get-kubeconfig
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: clusterName
                  value: "$(tasks.provision-cluster.results.clusterName)"
                - name: credentials
                  value: credentials
            - name: prepare-mvo-env
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/securesign/pipelines.git
                  - name: revision
                    value: mvo-e2e
                  - name: pathInRepo
                    value: stepactions/integration-test/prepare-mvo-env.yaml
              params:
                - name: credentials
                  value: credentials
                - name: KUBECONFIG
                  value: "$(steps.get-kubeconfig.results.kubeconfig)"
                - name: workdir
                  value: $(workspaces.source-code.path)/operator
                - name: mvo-namespace
                  value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
                - name: mvo-e2e-namespace
                  value: "$(params.MODEL_VALIDATION_OPERATOR_E2E_NS)"
      - name: install-operator-from-bundle
        runAfter:
          - provision-cluster
          - parse-metadata
          - prepare-env
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/install-operator-from-bundle.yaml
        params:
          - name: eaasSpaceSecretRef
            value: $(tasks.provision-eaas-space.results.secretRef)
          - name: clusterName
            value: "$(tasks.provision-cluster.results.clusterName)"
          - name: bundleImage
            value: "$(tasks.parse-metadata.results.container-image)"
          - name: namespace
            value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
        when:
          - input: "$(tasks.parse-metadata.results.component-name)"
            operator: in
            values: [ "model-validation-operator-bundle" ]
      - name: install-operator-from-image
        runAfter:
          - provision-cluster
          - parse-metadata
          - prepare-env
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/install-operator-from-image.yaml
        params:
          - name: eaasSpaceSecretRef
            value: $(tasks.provision-eaas-space.results.secretRef)
          - name: clusterName
            value: "$(tasks.provision-cluster.results.clusterName)"
          - name: operatorImage
            value: "$(tasks.parse-metadata.results.container-image)"
          - name: replaceImage
            value: "registry.redhat.io/rhtas/model-validation-rhel9-operator"
          - name: resourcesPath
            value: "$(workspaces.source-code.path)/config/overlays/olm"
          - name: namespace
            value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
          - name: deployName
            value: "model-validation-controller-manager"
        workspaces:
          - name: source-code
            workspace: work
        when:
          - input: "$(tasks.parse-metadata.results.component-name)"
            operator: in
            values: [ "model-validation-operator" ]
      - name: install-operator-from-fbc
        timeout: "0h5m0s"
        runAfter:
          - provision-cluster
          - parse-metadata
          - prepare-env
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/install-operator-from-fbc.yaml
        params:
          - name: eaasSpaceSecretRef
            value: $(tasks.provision-eaas-space.results.secretRef)
          - name: clusterName
            value: "$(tasks.provision-cluster.results.clusterName)"
          - name: fbcImage
            value: "$(tasks.parse-metadata.results.container-image)"
          - name: operator-name
            value: "model-validation-operator"
          - name: operator-deployment-name
            value: "model-validation-controller-manager"
          - name: installChannel
            value: "stable"
        when:
          - input: "$(tasks.parse-metadata.results.component-name)"
            operator: in
            values: ["pco-fbc-v4-15","pco-fbc-v4-16","pco-fbc-v4-17","pco-fbc-v4-18","pco-fbc-v4-19"]
      - name: run-operator-e2e
        runAfter:
          - prepare-env
          - clone-operator-source-code
          - install-operator-from-image
          - install-operator-from-bundle
          - install-operator-from-fbc
        workspaces:
          - name: source-code
            workspace: work
        taskSpec:
          volumes:
            - name: credentials
              emptyDir: { }
          workspaces:
            - name: source-code
          steps:
            - name: get-kubeconfig
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: clusterName
                  value: "$(tasks.provision-cluster.results.clusterName)"
                - name: credentials
                  value: credentials
            - name: push-test-image
              image: quay.io/konflux-ci/buildah-task:latest@sha256:27400eaf836985bcc35182d62d727629f061538f61603c05b85d5d99bfa7da2d
              securityContext:
                runAsUser: 0
                runAsNonRoot: false
                capabilities:
                  add:
                    - SETFCAP
              env:
                - name: MODEL_TRANSPARENCY_IMG
                  value: "$(params.MODEL_TRANSPARENCY_IMG)"
                - name: MODEL_VALIDATION_TEST_IMAGE
                  value: "$(params.MODEL_VALIDATION_TEST_IMAGE)"
              computeResources:
                limits:
                  memory: 8Gi
                requests:
                  memory: 2Gi
                  cpu: '1'
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
              workingDir: $(workspaces.source-code.path)/operator
              script: |
                #!/bin/sh
                set -euo pipefail

                echo "Installing packages..."
                if command -v microdnf >/dev/null 2>&1; then
                    microdnf install -y make openssl || microdnf install -y make openssl
                    microdnf install -y golang
                elif command -v dnf >/dev/null 2>&1; then
                    dnf install -y make openssl
                    dnf install -y golang
                elif command -v yum >/dev/null 2>&1; then
                    yum install -y make openssl
                    yum install -y golang
                elif command -v apt-get >/dev/null 2>&1; then
                    apt-get update -y && apt-get install -y make openssl
                    apt-get install -y golang-go
                else
                    echo "No supported package manager found to install packages"
                    exit 1
                fi
                echo "packages installed successfully"
                make --version || true

                # Make ALL buildah calls avoid fuse-overlayfs
                export BUILDAH_ISOLATION=chroot
                export STORAGE_DRIVER=vfs

                make e2e-generate-test-keys
                ls -la testdata/docker || true

                echo "Pulling latest Model transparency image..."
                buildah --storage-driver vfs pull "$MODEL_TRANSPARENCY_IMG"

                echo "Creating Model transparency container..."
                ctr="$(buildah --storage-driver vfs from "$MODEL_TRANSPARENCY_IMG")"

                echo "Adding storage..."
                buildah --storage-driver vfs add "$ctr" ./testdata/tensorflow_saved_model /model
                buildah --storage-driver vfs add "$ctr" ./testdata/docker/test_private_key.priv /test_private_key.priv
                buildah --storage-driver vfs config --entrypoint '[]' "$ctr"

                echo "Run singning using container image..."
                buildah --storage-driver vfs run --user 0 "$ctr" -- \
                  model_signing sign key /model \
                  --private_key /test_private_key.priv \
                  --signature /model/model.sig

                chmod -R 777 testdata/

                echo "Building test model image..."
                buildah --storage-driver vfs bud --no-cache --isolation=chroot \
                  -t "$MODEL_VALIDATION_TEST_IMAGE" -f testdata/docker/test-model.Dockerfile \
                  testdata

                echo "Pushing test model image..."
                buildah --storage-driver vfs push "$MODEL_VALIDATION_TEST_IMAGE"
                echo "Done."
            - name: execute-operator-e2e
              image: registry.redhat.io/ubi9/go-toolset:9.6@sha256:84286c7555df503df0bd3acb86fe2ad50af82a07f35707918bb0fad312fdc193
              env:
                - name: KUBECONFIG
                  value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
                - name: MODEL_VALIDATION_OPERATOR_E2E_NS
                  value: "$(params.MODEL_VALIDATION_OPERATOR_E2E_NS)"
                - name: MODEL_VALIDATION_OPERATOR_NS
                  value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
                - name: MODEL_VALIDATION_TEST_IMAGE
                  value: "$(params.MODEL_VALIDATION_TEST_IMAGE)"
              securityContext:
                runAsUser: 0
                capabilities:
                  add:
                    - SETFCAP
              computeResources:
                requests:
                  cpu: "1500m"
                  memory: "3Gi"
                limits:
                  cpu: "3"
                  memory: "6Gi"
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
              workingDir: $(workspaces.source-code.path)/operator
              script: |
                #!/usr/bin/env bash
                set -euo pipefail
                export KUBECONFIG="${KUBECONFIG:-/credentials/$(steps.get-kubeconfig.results.kubeconfig)}"
                NS="${MODEL_VALIDATION_OPERATOR_E2E_NS:-default}"

                echo "Working dir: $(pwd)"

                echo "Go to testdata..."
                cd test/e2e/testdata
                ls -la

                echo "Patch test image into DaemonSet manifest..."
                sed -i -E 's|(^[[:space:]]*image:[[:space:]]*).*|\1'"${MODEL_VALIDATION_TEST_IMAGE}"'|' model-data-daemonset.yaml

                echo "Install kubectl (client only)..."
                mkdir -p binaries
                curl -sSL -o binaries/kubectl "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                chmod +x binaries/kubectl
                export PATH="$(pwd)/binaries:$PATH"
                kubectl version --client || true

                echo "Ensuring namespace exists: $NS"
                kubectl get ns "$NS" >/dev/null 2>&1 || kubectl create ns "$NS"

                echo "Apply OpenShift SCC allowance for hostPath DaemonSet..."
                # This creates a ServiceAccount and RoleBinding to use the 'privileged' SCC
                kubectl apply -n "$NS" -f model-data-scc.yaml

                echo "Deploy model-data setup DaemonSet..."
                kubectl delete daemonset model-data-setup -n "$NS" --ignore-not-found
                kubectl apply -n "$NS" -f model-data-daemonset.yaml

                echo "Wait for DaemonSet rollout (5m)..."
                if ! kubectl rollout status daemonset/model-data-setup -n "$NS" --timeout=5m; then
                  echo "DaemonSet failed to roll out. Recent events:"
                  kubectl get ds model-data-setup -n "$NS" -o yaml | sed -n '1,120p' || true
                  kubectl get pods -n "$NS" -o wide || true
                  kubectl get events -n "$NS" --sort-by=.lastTimestamp | tail -n 80 || true
                  echo "Exiting due to DaemonSet rollout failure."
                  exit 1
                fi

                echo "Describe DaemonSet (namespace-scoped)..."
                kubectl describe daemonset/model-data-setup -n "$NS" || true

                echo "Starting e2e tests..."
                cd ../../..   # back to $(workspaces.source-code.path)/operator

                echo "Current dir: $(pwd)"

                make test-e2e