apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: operator-e2e-
spec:
  workspaces:
    - name: work
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  pipelineSpec:
    params:
      - name: SNAPSHOT
      - name: OCP_VERSION
        default: "4.19"
      - name: COMPUTE_NODE_TYPE
        default: m5.large
        description: Instance type for HyperShift compute nodes.
      - name: HOSTED_MANAGEMENT_CLUSTER
        default: hosted-mgmt2
        description: Hosted management cluster used to provision the ephemeral cluster.
      - name: OLMv1
        default: "false"
      - name: FIPS_ENABLED
        default: "false"
      - name: CLUSTER_PLATFORM
        description: "Target environment for Keycloak installation: openshift or kind"
        default: "openshift"
    workspaces:
      - name: work
        description: Shared workspace for pipeline tasks
    tasks:
      - name: parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/konflux-ci/tekton-integration-catalog
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/test-metadata/0.4/test-metadata.yaml
        params:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
      - name: release-info
        runAfter:
          - parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/derive-release-info.yaml
        params:
          - name: package-name
            value: "rhtas-operator"
          - name: fbc-image
            value: "$(tasks.parse-metadata.results.container-image)"
          - name: ocp-version
            value: $(params.OCP_VERSION)
      - name: clone-operator-source-code
        runAfter:
          - release-info
        taskRef:
          params:
            - name: name
              value: git-clone
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.2.6
            - name: kind
              value: task
          resolver: bundles
        params:
          - name: url
            value: "https://github.com/securesign/secure-sign-operator.git"
          - name: revision
            value: "$(tasks.release-info.results.release-branch)"
          - name: subdirectory
            value: "operator"
        workspaces:
          - name: output
            workspace: work
      - name: clone-e2e-test-source-code
        runAfter:
          - release-info
        taskRef:
          params:
            - name: name
              value: git-clone
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.2.6
            - name: kind
              value: task
          resolver: bundles
        params:
          - name: url
            value: https://github.com/securesign/sigstore-e2e
          - name: revision
            value: "$(tasks.release-info.results.release-branch)"
          - name: subdirectory
            value: "sigstore-e2e"
        workspaces:
          - name: output
            workspace: work
      - name: prepare-cluster-env
        taskSpec:
          workspaces:
            - name: env-files
          steps:
            - name: write-image-content-sources
              image: registry.redhat.io/ubi9/ubi-minimal:latest
              script: |
                #!/usr/bin/env sh
                mkdir -p "$(workspaces.env-files.path)/cluster-env"
                cat > "$(workspaces.env-files.path)/cluster-env/IMAGE_CONTENT_SOURCES" <<'EOF'
                - source: registry.redhat.io/rhtas/rhtas-operator-bundle
                  mirrors:
                    - quay.io/securesign/rhtas-operator-bundle
                    - quay.io/securesign/rhtas-operator-bundle-v1-0
                    - quay.io/securesign/rhtas-operator-bundle-v1-1
                    - quay.io/securesign/rhtas-operator-bundle-v1-2
                    - quay.io/securesign/rhtas-operator-bundle-v1-3
                - source: registry.redhat.io/rhtas/rhtas-rhel9-operator
                  mirrors:
                    - quay.io/securesign/rhtas-operator
                    - quay.io/securesign/rhtas-operator-v1-0
                    - quay.io/securesign/rhtas-operator-v1-1
                    - quay.io/securesign/rhtas-operator-v1-2
                    - quay.io/securesign/rhtas-operator-v1-3
                - source: registry.redhat.io/rhtas/trillian-logsigner-rhel9
                  mirrors:
                  - quay.io/securesign/trillian-logsigner
                - source: registry.redhat.io/rhtas/trillian-logserver-rhel9
                  mirrors:
                  - quay.io/securesign/trillian-logserver
                - source: registry.redhat.io/rhtas/trillian-database-rhel9
                  mirrors:
                  - quay.io/securesign/trillian-database
                - source: registry.redhat.io/rhtas/fulcio-rhel9
                  mirrors:
                  - quay.io/securesign/fulcio-server
                - source: registry.redhat.io/rhtas/trillian-redis-rhel9
                  mirrors:
                  - quay.io/securesign/trillian-redis
                - source: registry.redhat.io/rhtas/rekor-server-rhel9
                  mirrors:
                  - quay.io/securesign/rekor-server
                - source: registry.redhat.io/rhtas/rekor-search-ui-rhel9
                  mirrors:
                  - quay.io/securesign/rekor-search-ui
                - source: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9
                  mirrors:
                  - quay.io/securesign/rekor-backfill-redis
                - source: registry.redhat.io/rhtas/rekor-monitor-rhel9
                  mirrors:
                  - quay.io/securesign/rekor-monitor
                - source: registry.redhat.io/rhtas/ctlog-monitor-rhel9
                  mirrors:
                  - quay.io/securesign/ctlog-monitor
                - source: registry.redhat.io/rhtas/tuf-server-rhel9
                  mirrors:
                  - quay.io/securesign/scaffold-tuf-server
                - source: registry.redhat.io/rhtas/certificate-transparency-rhel9
                  mirrors:
                  - quay.io/securesign/certificate-transparency-go
                - source: registry.redhat.io/rhtas/client-server-cg-rhel9
                  mirrors:
                  - quay.io/securesign/cli-client-server-cg
                - source: registry.redhat.io/rhtas/client-server-re-rhel9
                  mirrors:
                  - quay.io/securesign/client-server-re
                - source: registry.redhat.io/rhtas/segment-reporting-rhel9
                  mirrors:
                  - quay.io/securesign/segment-backup-job
                - source: registry.redhat.io/rhtas/timestamp-authority-rhel9
                  mirrors:
                  - quay.io/securesign/timestamp-authority
                - source: registry.redhat.io/rhtas/createtree-rhel9
                  mirrors:
                  - quay.io/securesign/trillian-createtree
                - source: registry.redhat.io/rhtas/client-server-rhel9
                  mirrors:
                  - quay.io/securesign/client-server
                - source: registry.redhat.io/rhtas/tuffer-rhel9
                  mirrors:
                  - quay.io/securesign/tuffer
                - source: registry.redhat.io/rhtas/rhtas-console-ui-rhel9
                  mirrors:
                  - quay.io/securesign/rhtas-console-ui
                - source: registry.redhat.io/rhtas/rhtas-console-rhel9
                  mirrors:
                  - quay.io/securesign/rhtas-console
                - source: registry.redhat.io/rhtas/tufcli-init-rhel9
                  mirrors:
                  - quay.io/securesign/tufcli-init
                EOF
        workspaces:
          - name: env-files
            workspace: work
      - name: provision-cluster
        runAfter:
          - prepare-cluster-env
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/openshift/konflux-tasks
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/provision-ephemeral-cluster/0.1/provision-ephemeral-cluster.yaml
        workspaces:
          - name: env-files
            workspace: work
            subPath: cluster-env
        params:
          - name: ownerName
            value: $(context.pipelineRun.name)
          - name: ownerUid
            value: $(context.pipelineRun.uid)
          - name: workflow
            value: hypershift-hostedcluster-workflow
          - name: clusterProfile
            value: aws-konflux-prod
          - name: timeout
            value: 1h
          - name: env
            value: '{"COMPUTE_NODE_TYPE":"$(params.COMPUTE_NODE_TYPE)","FIPS":"$(params.FIPS_ENABLED)","HOSTED_MANAGEMENT_CLUSTER":"$(params.HOSTED_MANAGEMENT_CLUSTER)"}'
          - name: releases
            value: >-
              {"latest":{"release":{"channel":"stable","version":"$(params.OCP_VERSION)","architecture":"multi"}}}

      - name: install-operator-from-fbc
        timeout: "0h5m0s"
        runAfter:
          - provision-cluster
          - release-info
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/install-operator-from-fbc.yaml
        params:
          - name: clusterCredentialsSecretRef
            value: $(tasks.provision-cluster.results.secretRef)
          - name: fbcImage
            value: "$(tasks.parse-metadata.results.container-image)"
          - name: installChannel
            value: "$(tasks.release-info.results.channel)"
        when:
          - input: $(params.OLMv1)
            operator: notin
            values: ["true"]
      - name: install-operator-from-fbc-olmv1
        timeout: "0h5m0s"
        runAfter:
          - provision-cluster
          - parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/install-operator-from-fbc-olm-v1.yaml
        params:
          - name: clusterCredentialsSecretRef
            value: $(tasks.provision-cluster.results.secretRef)
          - name: fbcImage
            value: "$(tasks.parse-metadata.results.container-image)"
          - name: installChannel
            value: "$(tasks.release-info.results.channel)"
        when:
          - input: "$(params.OLMv1)"
            operator: in
            values: ["true"]
      - name: prepare-tests
        runAfter:
          - install-operator-from-fbc
          - install-operator-from-fbc-olmv1
          - clone-operator-source-code
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/prepare-tests.yaml
        params:
          - name: clusterCredentialsSecretRef
            value: $(tasks.provision-cluster.results.secretRef)
          - name: workdir
            value: "operator"
          - name: cluster-platform
            value: "$(params.CLUSTER_PLATFORM)"
        workspaces:
          - name: source-code
            workspace: work
      - name: download-binaries
        workspaces:
          - name: work
            workspace: work
        taskSpec:
          workspaces:
            - name: work
          steps:
            - name: get-tuftool
              image: registry.redhat.io/rhtas/tuftool-rhel9:1.3.0
              script: |
                mkdir -p $(workspaces.work.path)/binaries
                cp /usr/bin/tuftool $(workspaces.work.path)/binaries/
            - name: get-tufcli
              image: quay.io/securesign/tufcli@sha256:aac28072341cc8d24c2d4444ae1a058a6736898e9577e883fc469981043bcc88
              securityContext:
                runAsUser: 0
              script: |
                mkdir -p $(workspaces.work.path)/binaries
                cp /tufcli $(workspaces.work.path)/binaries/tufcli-bin
                cp /usr/lib64/libpcsclite.so.1 $(workspaces.work.path)/binaries/
                cat > $(workspaces.work.path)/binaries/tufcli <<'WRAPPER'
                #!/bin/sh
                LD_LIBRARY_PATH="${0%/*}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" exec "${0%/*}/tufcli-bin" "$@"
                WRAPPER
                chmod 0755 $(workspaces.work.path)/binaries/tufcli
            - name: get-cosign
              image: registry.redhat.io/rhtas/cosign-rhel9:1.3.1
              securityContext:
                runAsUser: 0
              script: |
                mkdir -p $(workspaces.work.path)/binaries
                cp /usr/local/bin/cosign $(workspaces.work.path)/binaries/
      - name: run-operator-e2e
        runAfter:
          - prepare-tests
          - download-binaries
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/operator-e2e.yaml
        params:
          - name: clusterCredentialsSecretRef
            value: $(tasks.provision-cluster.results.secretRef)
          - name: oidcHostname
            value: $(tasks.prepare-tests.results.oidc-hostname)
          - name: oidc-issuer-url
            value: $(tasks.prepare-tests.results.oidc-issuer-url)
          - name: fips-enabled
            value: "$(params.FIPS_ENABLED)"
        workspaces:
          - name: source-code
            workspace: work
      - name: run-tas-e2e
        runAfter:
          - prepare-tests
          - clone-e2e-test-source-code
        workspaces:
          - name: source-code
            workspace: work
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/securesign/pipelines.git
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/integration-test/sigstore-e2e.yaml
        params:
          - name: clusterCredentialsSecretRef
            value: $(tasks.provision-cluster.results.secretRef)
          - name: oidcHostname
            value: $(tasks.prepare-tests.results.oidc-hostname)
          - name: oidc-issuer-url
            value: $(tasks.prepare-tests.results.oidc-issuer-url)
    finally:
      - name: secure-push-test-dump
        workspaces:
         - name: dump
           workspace: work
        taskSpec:
          workspaces:
            - name: dump
          volumes:
            - name: push-creds
              secret:
                secretName: securesign-test-dump-oci
          steps:
            - name: oci-push
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/tekton-integration-catalog.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
              params:
                - name: oci-ref
                  value: "quay.io/securesign/test-dump-oci:$(context.pipelineRun.name)"
                - name: credentials-volume-name
                  value: push-creds
                - name: oci-tag-expiration
                  value: 1d
                - name: workdir-path
                  value: $(workspaces.dump.path)/dump
