apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-operator-from-bundle
spec:
  params:
    - name: clusterCredentialsSecretRef
      type: string
      description: Name of the secret containing the cluster admin kubeconfig.
    - name: bundleImage
      description: Operator bundle image to be installed
    - name: namespace
      default: "openshift-operators"
      description: Namespace to be used for installation
    - name: timeout
      description: Install bundle timeout
      default: "10m"
  volumes:
    - name: credentials
      secret:
        secretName: $(params.clusterCredentialsSecretRef)
  steps:
    - name: run-operator
      image: quay.io/operator-framework/operator-sdk:latest
      env:
        - name: KUBECONFIG
          value: "/credentials/kubeconfig"
      volumeMounts:
        - name: credentials
          mountPath: /credentials
      args:
        - run
        - bundle
        - --namespace
        - "$(params.namespace)"
        - --timeout
        - "$(params.timeout)"
        - "$(params.bundleImage)"
