apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - components/overlays/
  - fbc/overlays/
  - operator/overlays/
  - pco-fbc/overlays/
  - policy-controller-operator/overlays/
