---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: certificate-transparency-go
spec:
  componentName: certificate-transparency-go
  source:
    git:
      context: ./
      url: https://github.com/securesign/certificate-transparency-go
      revision: main
      dockerfileUrl: Dockerfile.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: rekor-monitor
spec:
  componentName: rekor-monitor
  source:
    git:
      context: ./
      url: https://github.com/securesign/rekor-monitor
      revision: main
      dockerfileUrl: Dockerfile.rekor-monitor.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: fulcio-server
spec:
  componentName: fulcio-server
  source:
    git:
      context: ./
      url: https://github.com/securesign/fulcio
      revision: main
      dockerfileUrl: Dockerfile.fulcio-server.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: backfill-redis
spec:
  componentName: backfill-redis
  source:
    git:
      context: ./
      url: https://github.com/securesign/rekor
      revision: main
      dockerfileUrl: Dockerfile.backfill-redis.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: rekor-server
spec:
  componentName: rekor-server
  source:
    git:
      context: ./
      url: https://github.com/securesign/rekor
      revision: main
      dockerfileUrl: Dockerfile.rekor-server.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: rekor-search
spec:
  componentName: rekor-search
  source:
    git:
      url: https://github.com/securesign/rekor-search-ui
      revision: main
      dockerfileUrl: Dockerfile
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: segment-backup-job
spec:
  componentName: segment-backup-job
  source:
    git:
      context: ./
      url: https://github.com/securesign/segment-backup-job
      revision: main
      dockerfileUrl: Dockerfile.segment-backup-job.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: timestamp-authority
spec:
  componentName: timestamp-authority
  source:
    git:
      url: https://github.com/securesign/timestamp-authority.git
      revision: main
      dockerfileUrl: Dockerfile.tsa.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: createtree
spec:
  componentName: createtree
  source:
    git:
      context: ./
      url: https://github.com/securesign/trillian
      revision: main
      dockerfileUrl: Dockerfile.createtree.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: database
spec:
  componentName: database
  source:
    git:
      context: ./
      url: https://github.com/securesign/trillian
      revision: main
      dockerfileUrl: Dockerfile.database.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: logserver
spec:
  componentName: logserver
  source:
    git:
      context: ./
      url: https://github.com/securesign/trillian
      revision: main
      dockerfileUrl: Dockerfile.logserver.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: logsigner
spec:
  componentName: logsigner
  source:
    git:
      context: ./
      url: https://github.com/securesign/trillian
      revision: main
      dockerfileUrl: Dockerfile.logsigner.rh
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
    config.kubernetes.io/path: 'tas-components/base/component.yaml'
    internal.config.kubernetes.io/path: 'tas-components/base/component.yaml'
  name: redis
spec:
  componentName: redis
  source:
    git:
      context: ./
      url: https://github.com/securesign/trillian
      revision: main
      dockerfileUrl: Dockerfile.redis.rh
---
