apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
    - name: output
  stepTemplate:
    env:
      - name: HOME
        value: /workspace
    image: quay.io/konflux-ci/task-runner:2.1.0@sha256:1d57720b2d1730ff2bb52b93d458eb14bfed759ec5267c2b532f776ff0bf8fab
    workingDir: /workspace/output/source
  params:
    - name: manifest
      type: string
      description: Manifest to apply
    - name: release
      type: string
      default: "false"
      description: whether or not to apply the manifest
  steps:
    - name: apply-manifest
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        echo "Applying: $(params.manifest)"
        cat "$(params.manifest)"
        echo ""

        if [ "$(params.release)" == "true" ]; then
          oc apply -f "$(params.manifest)"
        else
          echo "Performing DRY RUN"
          oc apply --dry-run=server -f "$(params.manifest)"
        fi
