apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
    - name: output
  stepTemplate:
    env:
      - name: HOME
        value: /workspace
    image: quay.io/konflux-ci/task-runner:2.0.0@sha256:80e5bf464f7732fb6232912a6ed4289e0773914b6ffe13f065026ba09437c790
    workingDir: /workspace/output/source
  params:
    - name: manifest
      type: string
      description: Manifest to apply
    - name: release
      type: string
      default: "false"
      description: whether or not to apply the manifest
  steps:
    - name: apply-manifest
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        echo "Applying: $(params.manifest)"
        cat "$(params.manifest)"
        echo ""

        if [ "$(params.release)" == "true" ]; then
          oc apply -f "$(params.manifest)"
        else
          echo "Performing DRY RUN"
          oc apply --dry-run=server -f "$(params.manifest)"
        fi
