apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
    - name: output
  stepTemplate:
    env:
      - name: HOME
        value: /workspace
    image: quay.io/konflux-ci/appstudio-utils:48c311af02858e2422d6229600e9959e496ddef1@sha256:91ddd999271f65d8ec8487b10f3dd378f81aa894e11b9af4d10639fd52bba7e8
    workingDir: /workspace/output/source
  params:
    - name: manifest
      type: string
      description: Manifest file or kustomize directory to apply
    - name: release
      type: string
      default: "false"
      description: whether or not to apply the manifest
  steps:
    - name: apply-manifest
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        echo "Processing: $(params.manifest)"

        # Check if it's a directory (kustomize) or file (manifest)
        if [ -d "$(params.manifest)" ]; then
          echo "Detected kustomize directory: $(params.manifest)"
          if [ "$(params.release)" == "true" ]; then
            echo "Applying kustomization..."
            oc apply -k "$(params.manifest)"
          else
            echo "Performing DRY RUN on kustomization"
            oc apply --dry-run=server -k "$(params.manifest)"
          fi
        elif [ -f "$(params.manifest)" ]; then
          echo "Detected manifest file: $(params.manifest)"
          cat "$(params.manifest)"
          echo ""
          if [ "$(params.release)" == "true" ]; then
            oc apply -f "$(params.manifest)"
          else
            echo "Performing DRY RUN on manifest"
            oc apply --dry-run=server -f "$(params.manifest)"
          fi
        else
          echo "ERROR: $(params.manifest) is neither a file nor a directory"
          exit 1
        fi
