---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: fips-check
spec:
  description: >-
    The fips-check task uses the check-payload tool to verify if an image is FIPS compliant.
  params:
    - name: image-digest
      description: Image digest to scan.
    - name: image-url
      description: Image URL.
  stepTemplate:
    volumeMounts:
      - name: workdir
        mountPath: /var/workdir
    workingDir: /var/workdir
  volumes:
    - name: workdir
      emptyDir: {}
  steps:
    - name: fetch-oci-artifact
      image: quay.io/konflux-ci/konflux-test:v1.4.34@sha256:62a7bf68015c711e0eb0698c10d203d0393a8e0efa09306f1fce543dea383f3c
      env:
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
        - name: IMAGE_URL
          value: $(params.image-url)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        skopeo copy --remove-signatures "docker://${IMAGE_URL}" "oci:oci:bundle"
        umoci unpack --rootless --image oci:bundle unpacked

    - name: fips-check
      image: quay.io/konflux-ci/konflux-test:v1.4.34@sha256:62a7bf68015c711e0eb0698c10d203d0393a8e0efa09306f1fce543dea383f3c
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        check-payload scan local --path /var/workdir/unpacked/rootfs
