apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-operator-from-bundle
spec:
  params:
    - name: eaasSpaceSecretRef
      type: string
      description: Name of a secret containing credentials for accessing an EaaS space.
    - name: clusterName
      type: string
      description: The name of a ClusterTemplateInstance.
    - name: bundleImage
      description: Operator bundle image to be installed
    - name: namespace
      description: Namespace to be used for installation
    - name: timeout
      description: Install bundle timeout
      default: "10m"
  volumes:
    - name: credentials
      emptyDir: {}
  steps:
    - name: get-kubeconfig
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
      params:
        - name: eaasSpaceSecretRef
          value: "$(params.eaasSpaceSecretRef)"
        - name: clusterName
          value: "$(params.clusterName)"
        - name: credentials
          value: credentials
    - name: run-operator
      image: quay.io/operator-framework/operator-sdk:latest
      env:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
      volumeMounts:
        - name: credentials
          mountPath: /credentials
      args:
        - run
        - bundle
        - --namespace
        - "$(params.namespace)"
        - --timeout
        - "$(params.timeout)"
        - "$(params.bundleImage)"