apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-operator-from-image
spec:
  params:
    - name: eaasSpaceSecretRef
      type: string
      description: Name of a secret containing credentials for accessing an EaaS space.
    - name: clusterName
      type: string
      description: The name of a ClusterTemplateInstance.
    - name: operatorImage
      description: Operator image to be installed
    - name: namespace
      description: Namespace to be used for installation
    - name: resources_url
      description: Resource directory to be kustomized and applied
  volumes:
    - name: credentials
      emptyDir: { }
    - name: resources
      emptyDir: { }
  steps:
    - name: get-kubeconfig
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
      params:
        - name: eaasSpaceSecretRef
          value: "$(params.eaasSpaceSecretRef)"
        - name: clusterName
          value: "$(params.clusterName)"
        - name: credentials
          value: credentials
    - name: kustomize-resources
      image: registry.k8s.io/kustomize/kustomize:v5.6.0
      volumeMounts:
        - name: resources
          mountPath: /storage
      script: |
        #!/bin/sh
        echo "getting resources from $(params.resources_url)"
        kustomize localize --no-verify "$(params.resources_url)" /storage/resources
        cd /storage/resources/config/manager && kustomize edit set image controller=$(params.operatorImage)
        echo "I am going to install following resources"
        kustomize build /storage/resources/config/env/openshift

    - name: run-operator
      image: registry.redhat.io/openshift4/ose-cli
      env:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
      volumeMounts:
        - name: credentials
          mountPath: /credentials
        - name: resources
          mountPath: /storage
      script: |
        oc create -k /storage/resources/config/env/openshift
        oc wait --for=condition=available deployment/rhtas-controller-manager --timeout=120s -n openshift-rhtas-operator
