apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-metadata
spec:
  results:
    - name: test-event-type
      description: "Stores information about the event type that indicates if a job is running for a Pull Request or Push event"
    - name: application-name
      description: "Stores information about the Konflux application that the Snapshot was created for."
    - name: component
      description: "Stores information about the Konflux component that was built."
    - name: image
      description: "Stores information about the component's container that was built in case of the component-type Snapshot."
    - name: git-url
      description: "Stores information about the component's source url."
    - name: git-revision
      description: "Stores information about the component's source revision."
  params:
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test
  steps:
    - name: test-metadata
      image: quay.io/redhat-appstudio/konflux-test:stable
      workingDir: /workspace
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: EVENT_TYPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/event-type']
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: APPLICATION_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/application']
      script: |
        #!/bin/sh

        # Derive additional environment variables from SNAPSHOT
        IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")
        GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .source.git.url' <<< "${SNAPSHOT}")
        GIT_REVISION=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .source.git.revision' <<< "${SNAPSHOT}")

        # Log declared environment variables
        echo "Snapshot metadata:"
        echo "  SNAPSHOT: ${SNAPSHOT}"
        echo "  EVENT_TYPE: ${EVENT_TYPE}"
        echo "  APPLICATION_NAME: ${APPLICATION_NAME}"
        echo "  COMPONENT: ${COMPONENT_NAME}"
        echo "  IMAGE: ${IMAGE}"
        echo "  GIT_URL: ${GIT_URL}"
        echo "  GIT_REVISION: ${GIT_REVISION}"

        # Write each environment variable to its respective results:
        echo -n "${EVENT_TYPE}" > $(results.test-event-type.path)
        echo -n "${APPLICATION_NAME}" > $(results.application-name.path)
        echo -n "${COMPONENT_NAME}" > $(results.component.path)
        echo -n "${IMAGE}" > $(results.image.path)
        echo -n "${GIT_URL}" > $(results.git-url.path)
        echo -n "${GIT_REVISION}" > $(results.git-revision.path)
