apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - project.yaml
  - template.yaml

patches:
  - target:
      name: rhtas-fbc-project-template
      kind: ProjectDevelopmentStreamTemplate
    path: ec-patch.yaml
