apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      name: ansible-template
      kind: ProjectDevelopmentStreamTemplate
    path: collection-patch.yaml
  - target:
      name: ansible-template
      kind: ProjectDevelopmentStreamTemplate
    path: ec-patch.yaml
