apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - template.yaml

components:
  - ../../base/ec
  - ../../base/monorepo

patches:
  - target:
      name: model-validation-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/manager.yaml
  - target:
      name: model-validation-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/imagerepository.yaml
  - target:
      name: model-validation-operator-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/bundle.yaml
