apiVersion: projctl.konflux.dev/v1beta1
kind: Project
metadata:
  name: operator
spec:
  displayName: "Model Validation Operator"
  description: |
    The Model Validation Operator allows for the deployment of a production ready version of the SigStore project.
