apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: rhtas-console
spec:
  project: rhtas-console
  template:
    name: rhtas-console-template
    values:
      - name: version
        value: "main"
      - name: branch
        value: "main"
      - name: nameSuffix
        value: ""