---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: konflux-configuration-as-code-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: konflux-configuration-as-code-role
rules:
  - apiGroups: ["appstudio.redhat.com"]
    resources: ["applications", "components", "integrationtestscenarios", "releaseplans", "snapshots", "imagerepositories"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["projctl.konflux.dev"]
    resources: ["projects", "projectdevelopmentstreamtemplates", "projectdevelopmentstreams"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: konflux-configuration-as-code-deployer-rolebinding
subjects:
  - kind: ServiceAccount
    name: konflux-configuration-as-code-deployer
roleRef:
  kind: Role
  name: konflux-configuration-as-code-role
  apiGroup: rbac.authorization.k8s.io
---
