apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: model-validation-operator-e2e
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys the model validation operator
    from a Konflux snapshot and run the e2e test suite.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    - description: OCP version
      name: OCP_VERSION
      type: string
      default: "4.17"
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
    - description: RHTAS Bundle image
      name: RHTAS_BUNDLE_IMAGE
      default: registry.redhat.io/rhtas/rhtas-operator-bundle:1.2.0
      type: string
    - description: RHTAS git url
      name: RHTAS_GIT_URL
      default: https://github.com/securesign/secure-sign-operator
      type: string
    - description: RHTAS git revision
      name: RHTAS_GIT_REVISION
      default: main
      type: string
    - description: Namespace where TAS will be installed
      name: TAS_E2E_NAMESPACE
      default: tas-e2e
      type: string
    - description: Namespace where Model Validation Operator will be installed
      name: MODEL_VALIDATION_OPERATOR_NS
      default: model-validation-operator
      type: string
    - description: Model Validation operator Git Url
      name: MODEL_VALIDATION_OPERATOR_GIT_URL
      default: https://github.com/securesign/model-validation-operator
      type: string
  tasks:
    - name: parse-metadata
    #   taskRef:
    #     resolver: git
    #     params:
    #       - name: url
    #         value: https://github.com/securesign/pipelines.git
    #       - name: revision
    #         value: main
    #       - name: pathInRepo
    #         value: tasks/parse-metadata.yaml
    #   params:
    #     - name: SNAPSHOT
    #       value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      runAfter:
        - parse-metadata
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1-4e4fa7355a6a51083954408e7e3b647e3bddb8d8
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(params.OCP_VERSION)"
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.large
              - name: timeout
                value: 60m
              - name: imageContentSources
                value: |
                  - source: registry.redhat.io/rhtas/model-validation-operator-bundle
                    mirrors:
                      - quay.io/securesign/model-validation-operator-bundle
                  - source: registry.redhat.io/rhtas/model-validation-operator
                    mirrors:
                      - quay.io/securesign/model-validation-operator
    - name: install-rhtas-operator
      runAfter:
        - provision-cluster
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-bundle.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: bundleImage
          value: "$(params.RHTAS_BUNDLE_IMAGE)"
        - name: namespace
          value: "$(params.NAMESPACE)"
    - name: install-securesign
      runAfter:
        - install-rhtas-operator
      params:
        - name: namespace
          value: "$(params.NAMESPACE)"
      taskSpec:
        results:
          - name: oidc-hostname
            value: "$(steps.install-keycloak.results.oidc-hostname)"
        volumes:
          - name: credentials
            emptyDir: { }
          - name: repository
            emptyDir: { }
          - name: binaries
            emptyDir: { }
          - name: dump
            emptyDir: { }
          - name: push-creds
            secret:
              secretName: securesign-test-dump-oci
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: git-clone-operator
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/git-clone.yaml
            params:
              - name: url
                value: "$(params.RHTAS_GIT_URL)"
              - name: revision
                value: "$(params.RHTAS_GIT_REVISION)"
              - name: repository
                value: repository
          - name: install-keycloak
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/install-keycloak.yaml
            params:
              - name: credentials
                value: credentials
              - name: repository
                value: repository
              - name: KUBECONFIG
                value: "$(steps.get-kubeconfig.results.kubeconfig)"
              - name: workdir
                value: source
          - name: install-tas
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/install-tas.yaml
            params:
              - name: credentials
                value: credentials
              - name: repository
                value: repository
              - name: KUBECONFIG
                value: "$(steps.get-kubeconfig.results.kubeconfig)"
              - name: workdir
                value: source
              - name: tas-namespace
                value: "$(params.TAS_E2E_NAMESPACE)"
              - name: OIDC_HOST
                value: "$(steps.install-keycloak.results.oidc-hostname)"
    - name: install-operator-from-bundle
      runAfter:
        - install-securesign
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-bundle.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: openshift-operators #"$(params.NAMESPACE)"
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "model-validation-operator-bundle" ]
    - name: model-validation-operator-e2e
      runAfter:
        - install-operator-from-bundle
      params:
        - name: namespace
          value: openshift-operators # "$(params.NAMESPACE)"
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: { }
          - name: repository
            emptyDir: { }
          - name: binaries
            emptyDir: { }
          - name: dump
            emptyDir: { }
        steps:
          - name: get-oc
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/extract-oc.yaml
            params:
              - name: volume
                value: binaries
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: git-clone-mvo
            image: registry.redhat.io/ubi9/go-toolset:9.6@sha256:84286c7555df503df0bd3acb86fe2ad50af82a07f35707918bb0fad312fdc193
            env:
              - name: GIT_URL
                value: "$(params.MODEL_VALIDATION_OPERATOR_GIT_URL)"
              - name: GIT_REVISION
                value: "$(tasks.parse-metadata.results.git-revision)"
            volumeMounts:
              - name: repository
                mountPath: /repository
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              cd /repository
              echo "Cloning Model Validation Operator"
              git clone "$GIT_URL" source
              cd source
              if [ "$(tasks.parse-metadata.results.git-url)" == "$(params.MODEL_VALIDATION_OPERATOR_GIT_URL)" ]; then
                git checkout "$GIT_REVISION"
              fi
          - name: execute-operator-e2e
            image: registry.redhat.io/ubi9/go-toolset:9.6@sha256:84286c7555df503df0bd3acb86fe2ad50af82a07f35707918bb0fad312fdc193
            env:
              - name: MODEL_TRANSPARENCY_IMG
                value: quay.io/securesign/model-transparency@sha256:6db7fa2b956875a6f507811166b47b164d463dea78ab4403c6d7648d838b8acb
              - name: OIDC_HOST
                value: "$(tasks.install-securesign.results.oidc-hostname)"
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
              - name: RHTAS_INSTALL_NAMESPACE
                value: "$(params.TAS_E2E_NAMESPACE)"
              - name: MODEL_VALIDATION_OPERATOR_NS
                value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
            computeResources:
              requests:
                cpu: "1500m"
                memory: "3Gi"
              limits:
                cpu: "3"
                memory: "6Gi"
            volumeMounts:
              - name: repository
                mountPath: /repository
              - name: binaries
                mountPath: /binaries
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/sh
              set +e -o pipefail
              curl -sSL -o /binaries/kubectl https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
              chmod +x /binaries/kubectl
              cd /repository/source
              export PATH="$PATH:/binaries"
              make test-e2e-ci MODEL_TRANSPARENCY_IMG="$MODEL_TRANSPARENCY_IMG"
              status=$?

              if [[ $status -ne 0 ]]; then
                pods=$(oc get pods -n "$MODEL_VALIDATION_OPERATOR_NS" -o jsonpath='{.items[*].metadata.name}')
                for pod in $pods; do
                  echo "===== logs for $pod ====="
                  oc logs -n "$MODEL_VALIDATION_OPERATOR_NS" --all-containers --prefix "$pod" "$pod" || true
                done
              fi

              exit "$status"
