apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: model-validation-operator-e2e
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys the model validation operator
    from a Konflux snapshot and run the e2e test suite.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    - description: OCP version
      name: OCP_VERSION
      type: string
      default: "4.17"
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
    - description: Namespace where Model Validation Operator will be installed
      name: MODEL_VALIDATION_OPERATOR_NS
      default: model-validation-operator-system
      type: string
    - description: Model Validation operator Git Url
      name: MODEL_VALIDATION_OPERATOR_GIT_URL
      default: https://github.com/securesign/model-validation-operator
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/parse-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      runAfter:
        - parse-metadata
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1-4e4fa7355a6a51083954408e7e3b647e3bddb8d8
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(params.OCP_VERSION)"
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.large
              - name: timeout
                value: 60m
              - name: imageContentSources
                value: |
                  - source: registry.redhat.io/rhtas/model-validation-operator-bundle
                    mirrors:
                      - quay.io/securesign/model-validation-operator-bundle
                  - source: registry.redhat.io/rhtas/model-validation-operator
                    mirrors:
                      - quay.io/securesign/model-validation-operator
                  - source: registry.redhat.io/rhtas/model-validation-rhel9-operator
                    mirrors:
                      - quay.io/securesign/model-validation-operator
    - name: install-operator-from-bundle
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-bundle.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
        - name: timeout
          value: 30m
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "model-validation-operator-bundle" ]
    - name: install-operator-from-image
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-image.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: operatorImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: deployName
          value: "model-validation-controller-manager"
        - name: namespace
          value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
        - name: resources_url
          value: "$(tasks.parse-metadata.results.git-url).git/config/overlays/olm?ref=$(tasks.parse-metadata.results.git-revision)"
        - name: resources_path
          value: config/overlays/olm

      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "model-validation-operator" ]
    - name: model-validation-operator-e2e
      runAfter:
        - install-operator-from-image
        - install-operator-from-bundle
        - install-operator-from-fbc
      params:
        - name: namespace
          value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: { }
          - name: repository
            emptyDir: { }
          - name: binaries
            emptyDir: { }
          - name: dump
            emptyDir: { }
        steps:
          - name: get-oc
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/extract-oc.yaml
            params:
              - name: volume
                value: binaries
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: git-clone-mvo
            image: registry.redhat.io/ubi9/go-toolset:9.6@sha256:84286c7555df503df0bd3acb86fe2ad50af82a07f35707918bb0fad312fdc193
            env:
              - name: GIT_URL
                value: "$(params.MODEL_VALIDATION_OPERATOR_GIT_URL)"
              - name: GIT_REVISION
                value: "$(tasks.parse-metadata.results.git-revision)"
            volumeMounts:
              - name: repository
                mountPath: /repository
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              cd /repository
              echo "Cloning Model Validation Operator"
              git clone "$GIT_URL" source
              cd source
              if [ "$(tasks.parse-metadata.results.git-url)" == "$(params.MODEL_VALIDATION_OPERATOR_GIT_URL)" ]; then
                git checkout "$GIT_REVISION"
              fi
          - name: execute-operator-e2e
            image: registry.redhat.io/ubi9/go-toolset:9.6@sha256:84286c7555df503df0bd3acb86fe2ad50af82a07f35707918bb0fad312fdc193
            env:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
              - name: MODEL_VALIDATION_OPERATOR_NS
                value: "$(params.MODEL_VALIDATION_OPERATOR_NS)"
              - name: MODEL_VALIDATION_OPERATOR_E2E_NS
                value: e2e-webhook-test-ns
            computeResources:
              requests:
                cpu: "1500m"
                memory: "3Gi"
              limits:
                cpu: "3"
                memory: "6Gi"
            volumeMounts:
              - name: repository
                mountPath: /repository
              - name: binaries
                mountPath: /binaries
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/sh
              set +e -o pipefail
              curl -sSL -o /binaries/kubectl https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
              chmod +x /binaries/kubectl
              cd /repository/source
              export PATH="$PATH:/binaries"
              MODEL_VALIDATION_OPERATOR_E2E_NS="${MODEL_VALIDATION_OPERATOR_E2E_NS:-e2e-webhook-test-ns}"
              oc projects
              oc project $MODEL_VALIDATION_OPERATOR_NS
              oc create ns $MODEL_VALIDATION_OPERATOR_E2E_NS

              make test-e2e
              status=$?

              if [[ $status -ne 0 ]]; then
                pods=$(oc get pods -n "$MODEL_VALIDATION_OPERATOR_NS" -o jsonpath='{.items[*].metadata.name}')
                for pod in $pods; do
                  echo "===== logs for $pod ====="
                  oc logs -n "$MODEL_VALIDATION_OPERATOR_NS" --all-containers --prefix "$pod" "$pod" || true
                done
              fi

              exit "$status"
