apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: model-validation-operator-e2e
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys the model validation operator
    from a Konflux snapshot and run the e2e test suite.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    - description: OCP version
      name: OCP_VERSION
      type: string
      default: "4.17"
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
    - description: Namespace where Model Validation Operator will be installed
      name: MODEL_VALIDATION_OPERATOR_NS
      default: model-validation-operator
      type: string
    - description: Model Validation operator Git Url
      name: MODEL_VALIDATION_OPERATOR_GIT_URL
      default: https://github.com/securesign/model-validation-operator
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/parse-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      runAfter:
        - parse-metadata
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1-4e4fa7355a6a51083954408e7e3b647e3bddb8d8
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(params.OCP_VERSION)"
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.large
              - name: timeout
                value: 60m
              - name: imageContentSources
                value: |
                  - source: registry.redhat.io/rhtas/model-validation-operator-bundle
                    mirrors:
                      - quay.io/securesign/model-validation-operator-bundle
                  - source: registry.redhat.io/rhtas/model-validation-operator
                    mirrors:
                      - quay.io/securesign/model-validation-operator
    - name: install-operator-from-bundle
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-bundle.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.NAMESPACE)"
        - name: timeout
          value: 30m
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "model-validation-operator-bundle" ]
    - name: install-operator-from-image
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-image.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: operatorImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: resources_url
          value: "$(tasks.parse-metadata.results.git-url).git/config/env/openshift?ref=$(tasks.parse-metadata.results.git-revision)"
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "model-validation-operator" ]