apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: operator-e2e
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys the operator
    bundle from a Konflux snapshot and run the e2e test suite.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    - description: OCP version
      name: OCP_VERSION
      type: string
      default: "4.17"
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/parse-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1-0351e1e3df028e27e43877d9ca7e646be4ff2d65
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(params.OCP_VERSION)"
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.large
              - name: timeout
                value: 40m
              - name: imageContentSources
                value: |
                  - source: registry.redhat.io/rhtas/rhtas-operator-bundle
                    mirrors:
                      - quay.io/securesign/rhtas-operator-bundle
                      - quay.io/securesign/rhtas-operator-bundle-v1-0
                      - quay.io/securesign/rhtas-operator-bundle-v1-1
                  - source: registry.redhat.io/rhtas/rhtas-rhel9-operator
                    mirrors:
                      - quay.io/securesign/rhtas-operator
                      - quay.io/securesign/rhtas-operator-v1-0
                      - quay.io/securesign/rhtas-operator-v1-1
                  - source: registry.redhat.io/rhtas/trillian-logsigner-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-logsigner
                  - source: registry.redhat.io/rhtas/trillian-logserver-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-logserver
                  - source: registry.redhat.io/rhtas/trillian-database-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-database
                  - source: registry.redhat.io/rhtas/fulcio-rhel9
                    mirrors:
                    - quay.io/securesign/fulcio-server
                  - source: registry.redhat.io/rhtas/trillian-redis-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-redis
                  - source: registry.redhat.io/rhtas/rekor-server-rhel9
                    mirrors:
                    - quay.io/securesign/rekor-server
                  - source: registry.redhat.io/rhtas/rekor-search-ui-rhel9
                    mirrors:
                    - quay.io/securesign/rekor-search-ui
                  - source: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-redis
                  - source: registry.redhat.io/rhtas/tuf-server-rhel9
                    mirrors:
                    - quay.io/securesign/scaffold-tuf-server
                  - source: registry.redhat.io/rhtas/certificate-transparency-rhel9
                    mirrors:
                    - quay.io/securesign/certificate-transparency-go
                  - source: registry.redhat.io/rhtas/client-server-cg-rhel9
                    mirrors:
                    - quay.io/securesign/cli-client-server-cg
                  - source: registry.redhat.io/rhtas/client-server-re-rhel9
                    mirrors:
                    - quay.io/securesign/client-server-re
                  - source: registry.redhat.io/rhtas/segment-reporting-rhel9
                    mirrors:
                    - quay.io/securesign/segment-backup-job
                  - source: registry.redhat.io/rhtas/timestamp-authority-rhel9
                    mirrors:
                    - quay.io/securesign/timestamp-authority
                  - source: registry.redhat.io/rhtas/trillian-createtree-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-createtree
                  - source: registry.redhat.io/rhtas/client-server-rhel9
                    mirrors:
                    - quay.io/securesign/client-server
                  - source: registry.redhat.io/rhtas/tuffer-rhel9
                    mirrors:
                    - quay.io/securesign/tuffer
    - name: install-operator-from-bundle
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-bundle.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.NAMESPACE)"
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "rhtas-operator-bundle" ]
    - name: install-operator-from-image
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-image.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: operatorImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.NAMESPACE)"
        - name: resources_url
          value: "$(tasks.parse-metadata.results.git-url).git/config/env/openshift?ref=$(tasks.parse-metadata.results.git-revision)"
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "rhtas-operator" ]
    - name: install-operator-from-fbc
      timeout: "0h5m0s"
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-fbc.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: fbcImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.NAMESPACE)"
      # replace with cel regexp once enabled https://issues.redhat.com/browse/KFLUXSPRT-1833
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: [ "fbc-v4-17", "fbc-v4-16", "fbc-v4-15", "fbc-v4-14", "fbc-v4-13" ]
    - name: run-e2e
      runAfter:
        # run after either one
        - install-operator-from-image
        - install-operator-from-bundle
        - install-operator-from-fbc
      params:
        - name: namespace
          value: "$(params.NAMESPACE)"
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: { }
          - name: repository
            emptyDir: { }
          - name: binaries
            emptyDir: { }
          - name: dump
            emptyDir: { }
          - name: push-creds
            secret:
              secretName: securesign-test-dump-oci
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          # workaround - IntegrationTest pipelines does not support workspaces ATM - it is not possible to use git-clone task
          - name: git-clone
            image: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:6a4a05d24acecde63d9c7c8c986ad9e5e20da2c2ce30312b328ed771736e7a1f
            volumeMounts:
              - name: repository
                mountPath: /repository
            script: |
              cd /repository
              if [[ "$(tasks.parse-metadata.results.component)" == "rhtas-operator" || "$(tasks.parse-metadata.results.component)" == "rhtas-operator-bundle" ]]; then
                echo "Cloning from $(tasks.parse-metadata.results.git-url)"
                git clone "$(tasks.parse-metadata.results.git-url)" source
                cd source
                git checkout $(tasks.parse-metadata.results.git-revision)
              else
                echo "Cloning from default url"
                git clone "https://github.com/securesign/secure-sign-operator.git" source
                cd source
              fi
          - name: install-keycloak
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/install-keycloak.yaml
            params:
              - name: credentials
                value: credentials
              - name: repository
                value: repository
              - name: KUBECONFIG
                value: "$(steps.get-kubeconfig.results.kubeconfig)"
              - name: workdir
                value: source
          - name: install-tas
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: ppinkas/konflux-e2e
                - name: pathInRepo
                  value: stepactions/install-tas.yaml
            params:
              - name: credentials
                value: credentials
              - name: repository
                value: repository
              - name: KUBECONFIG
                value: "$(steps.get-kubeconfig.results.kubeconfig)"
              - name: workdir
                value: source
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
          - name: git-clone-tas-e2e
            image: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:6a4a05d24acecde63d9c7c8c986ad9e5e20da2c2ce30312b328ed771736e7a1f
            volumeMounts:
              - name: repository
                mountPath: /repository
            script: |
              cd /repository
              echo "Cloning TAS e2e tests"
              git clone "https://github.com/securesign/sigstore-e2e" sigstore-e2e
          - name: prepare-tas-e2e
            image: registry.redhat.io/openshift4/ose-cli
            onError: continue
            volumeMounts:
              - name: repository
                mountPath: /repository
              - name: credentials
                mountPath: /credentials
            env:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
            script: |
              oc status
              cd /repository/sigstore-e2e
              ./tas-env-variables.sh > .env
          - name: execute-tas-e2e
            image: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:6a4a05d24acecde63d9c7c8c986ad9e5e20da2c2ce30312b328ed771736e7a1f
            onError: continue
            volumeMounts:
              - name: credentials
                mountPath: /credentials
              - name: repository
                mountPath: /repository
              - name: binaries
                mountPath: /binaries
              - name: dump
                mountPath: /dump
            script: |
              export PATH="$PATH:/binaries"
              echo "Path: $PATH"
              cd /repository/sigstore-e2e
              go mod vendor
              make build test
