apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: operator-e2e
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys the operator
    bundle from a Konflux snapshot and run the e2e test suite.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    - description: OCP version
      name: OCP_VERSION
      type: string
      default: "4.17"
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/parse-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1-0351e1e3df028e27e43877d9ca7e646be4ff2d65
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(params.OCP_VERSION)"
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.large
              - name: imageContentSources
                value: |
                  - source: registry.redhat.io/rhtas/rhtas-rhel9-operator
                    mirrors:
                      - quay.io/securesign/rhtas-operator
                  - source: registry.redhat.io/rhtas/trillian-logsigner-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-logsigner
                  - source: registry.redhat.io/rhtas/trillian-logserver-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-logserver
                  - source: registry.redhat.io/rhtas/trillian-database-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-database
                  - source: registry.redhat.io/rhtas/fulcio-rhel9
                    mirrors:
                    - quay.io/securesign/fulcio-server
                  - source: registry.redhat.io/rhtas/trillian-redis-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-redis
                  - source: registry.redhat.io/rhtas/rekor-server-rhel9
                    mirrors:
                    - quay.io/securesign/rekor-server
                  - source: registry.redhat.io/rhtas/rekor-search-ui-rhel9
                    mirrors:
                    - quay.io/securesign/rekor-search-ui
                  - source: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-redis
                  - source: registry.redhat.io/rhtas/tuf-server-rhel9
                    mirrors:
                    - quay.io/securesign/scaffold-tuf-server
                  - source: registry.redhat.io/rhtas/certificate-transparency-rhel9
                    mirrors:
                    - quay.io/securesign/certificate-transparency-go
                  - source: registry.redhat.io/rhtas/client-server-cg-rhel9
                    mirrors:
                    - quay.io/securesign/cli-client-server-cg
                  - source: registry.redhat.io/rhtas/client-server-re-rhel9
                    mirrors:
                    - quay.io/securesign/client-server-re
                  - source: registry.redhat.io/rhtas/segment-reporting-rhel9
                    mirrors:
                    - quay.io/securesign/segment-backup-job
                  - source: registry.redhat.io/rhtas/timestamp-authority-rhel9
                    mirrors:
                    - quay.io/securesign/timestamp-authority
                  - source: registry.redhat.io/rhtas/trillian-createtree-rhel9
                    mirrors:
                    - quay.io/securesign/trillian-createtree
                  - source: registry.redhat.io/rhtas/client-server-rhel9
                    mirrors:
                    - quay.io/securesign/client-server
    - name: install-operator-from-bundle
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-bundle.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.NAMESPACE)"
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: ["rhtas-operator-bundle"]
    - name: install-operator-from-image
      runAfter:
        - provision-cluster
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/securesign/pipelines.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/install-operator-from-image.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: operatorImage
          value: "$(tasks.parse-metadata.results.image)"
        - name: namespace
          value: "$(params.NAMESPACE)"
        - name: resources_url
          value: "$(tasks.parse-metadata.results.git-url).git/config/default?ref=$(tasks.parse-metadata.results.git-revision)"
      when:
        - input: "$(tasks.parse-metadata.results.component)"
          operator: in
          values: ["rhtas-operator"]
    - name: run-e2e
      runAfter:
        # run after either one
        - install-operator-from-image
        - install-operator-from-bundle
      params:
        - name: namespace
          value: "$(params.NAMESPACE)"
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: {}
          - name: repository
            emptyDir: {}
          - name: binaries
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
           # workaround - IntegrationTest pipelines does not support workspaces ATM - it is not possible to use git-clone task
          - name: git-clone
            image: registry.access.redhat.com/ubi9/go-toolset@sha256:3b6d9307fc925bc7d0d231622e6d681844c1d9328818e1ab4a0c47472ae74270
            volumeMounts:
              - name: repository
                mountPath: /repository
            script: |
              cd /repository
              git clone $(tasks.parse-metadata.results.git-url) source
              cd source
              git checkout $(tasks.parse-metadata.results.git-revision)
          - name: install-keycloak
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/install-keycloak.yaml
            params:
              - name: credentials
                value: credentials
              - name: repository
                value: repository
              - name: KUBECONFIG
                value: "$(steps.get-kubeconfig.results.kubeconfig)"
              - name: workdir
                value: source
          - name: get-tuftool
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/extract-tuftool.yaml
            params:
              - name: volume
                value: binaries
          - name: get-cosign
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/securesign/pipelines.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/extract-cosign.yaml
            params:
              - name: volume
                value: binaries
          - name: execute-e2e
            image: registry.access.redhat.com/ubi9/go-toolset@sha256:3b6d9307fc925bc7d0d231622e6d681844c1d9328818e1ab4a0c47472ae74270
            env:
              - name: OIDC_HOST
                value: "$(steps.install-keycloak.results.oidc-hostname)"
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
            volumeMounts:
              - name: credentials
                mountPath: /credentials
              - name: repository
                mountPath: /repository
              - name: binaries
                mountPath: /binaries
            script: |
              cd /repository/source
              export PATH="$PATH:/binaries"
              export OIDC_ISSUER_URL=https://$OIDC_HOST/auth/realms/trusted-artifact-signer
              openssl s_client -connect $OIDC_HOST:443 > /tmp/ssl.cert
              export SSL_CERT_FILE=/tmp/ssl.cert
              make test-e2e
