- op: add
  path: /spec/resources/-
  value:
    apiVersion: appstudio.redhat.com/v1alpha1
    kind: Component
    metadata:
      annotations:
        build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
        build.appstudio.openshift.io/status: '{"pac":{"state":"enabled","merge-url":"https://github.com/securesign/artifact-signer-ansible/pull/259","configuration-time":"Wed, 07 Aug 2024 08:59:18 UTC"},"message":"done"}'
        mintmaker.appstudio.redhat.com/disabled: "{{.mintmakerDisabled}}"
      name: "artifact-signer-ansible{{.nameSuffix}}"
    spec:
      application: "{{.application}}{{.nameSuffix}}"
      componentName: "artifact-signer-ansible{{.nameSuffix}}"
      source:
        git:
          context: ./
          dockerfileUrl: Dockerfile
          revision: "{{.branch}}"
          url: https://github.com/securesign/artifact-signer-ansible
- op: add
  path: /spec/resources/-
  value:
    apiVersion: appstudio.redhat.com/v1alpha1
    kind: ImageRepository
    metadata:
      name: "artifact-signer-ansible{{.nameSuffix}}"
      annotations:
        image-controller.appstudio.redhat.com/update-component-image: 'true'
      labels:
        appstudio.redhat.com/application: "{{.application}}{{.nameSuffix}}"
        appstudio.redhat.com/component: "artifact-signer-ansible{{.nameSuffix}}"
    spec:
      image:
        name: rhtas-tenant/artifact-signer-ansible
        visibility: public
      notifications:
        - config:
            url: https://bombino.api.redhat.com/v1/sbom/quay/push
          event: repo_push
          method: webhook
          title: SBOM-event-to-Bombino