apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - template.yaml

components:
  - ../../base/ec
  - ../../base/ocp/v4.16
  - ../../base/ocp/v4.17
  - ../../base/ocp/v4.18
  - ../../base/ocp/v4.19
  - ../../base/ocp/v4.20
