apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1-3

resources:
  - rhtas-operator-stream.yaml
  - rhtas-fbc-stream.yaml

components:
  - ../../components/rhtas-fbc
  - ../../components/ocp/v4.16
  - ../../components/ocp/v4.17
  - ../../components/ocp/v4.18
  - ../../components/ocp/v4.19

configurations:
  - kustomizeconfig.yaml
