apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: extract-cosign
spec:
  description: >-
    This StepAction extract cosign binary from image to specified volume.
  params:
    - name: volume
      type: string
      description: Name of the volume to be used for extraction.
    - name: volumePath
      type: string
      description: The directory path to use.
      default: ""
    - name: cosign-image
      type: string
      description: Cosign image url
      default: registry.redhat.io/rhtas/cosign-rhel9:1.1.0-1730377925
  image: "$(params.cosign-image)"
  volumeMounts:
    - name: "$(params.volume)"
      mountPath: /binaries
  env:
    - name: VOLUME_PATH
      value: "$(params.volumePath)"
  script: cp /usr/local/bin/cosign /binaries$VOLUME_PATH
