apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: extract-tuftool
spec:
  description: >-
    This StepAction extract tuftool binary from image to specified volume.
  image: registry.redhat.io/rhtas/tuftool-rhel9:1.1.0-1730740139
  params:
    - name: volume
      type: string
      description: Name of the volume to be used for extraction.
    - name: volumePath
      type: string
      description: The directory path to use.
      default: ""
  volumeMounts:
    - name: "$(params.volume)"
      mountPath: /binaries
  env:
    - name: VOLUME_PATH
      value: "$(params.volumePath)"
  script: cp /usr/bin/tuftool /binaries$VOLUME_PATH
