apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: git-clone-operator
spec:
  description: >-
    This StepAction clones operator repository.
  image: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:6a4a05d24acecde63d9c7c8c986ad9e5e20da2c2ce30312b328ed771736e7a1f
  params:
    - name: operator-component
      type: string
      description: Operator component used (operator, operator-bundle, ...).
    - name: git-url
      type: string
      description: Operator repository url.
    - name: git-revision
      type: string
      description: Operator repository revision.
  volumeMounts:
    - name: repository
      mountPath: /repository
  script: |
    cd /repository
      if [[ "$(params.operator-component)" == "rhtas-operator" || "$(params.operator-component)" == "rhtas-operator-bundle" ]]; then
        echo "Cloning from $(params.git-url)"
        git clone "$(params.git-url)" source
        cd source
        git checkout $(params.git-revision)
      else
        echo "Cloning from default url"
        git clone "https://github.com/securesign/secure-sign-operator.git" source
        cd source
       fi
