apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: git-clone
spec:
  description: >-
    This StepAction clones git repository.
  image: registry.redhat.io/ubi9/go-toolset:1.24@sha256:6fd64cd7f38a9b87440f963b6c04953d04de65c35b9672dbd7f1805b0ae20d09
  params:
    - name: repository
      type: string
      description: Volume with resources to be applied.
    - name: dir
      type: string
      default: source
      description: Name of target directory.
    - name: url
      type: string
      default: https://github.com/securesign/secure-sign-operator.git
      description: Repository url.
    - name: revision
      type: string
      default: main
      description: Repository revision.
  env:
    - name: DIR
      value: "$(params.dir)"
    - name: URL
      value: "$(params.url)"
    - name: REVISION
      value: "$(params.revision)"
  volumeMounts:
    - name: "$(params.repository)"
      mountPath: /repository
  script: |
    set -e
    echo "Cloning from ${URL}#${DIR}"
    
    cd /repository
    git clone --depth=1 "${URL}" "${DIR}" --no-single-branch
    cd "${DIR}"
    git fetch --depth=1 origin "${REVISION}"
    git checkout "${REVISION}"