apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: git-clone-operator
spec:
  description: >-
    This StepAction clones operator repository.
  image: registry.redhat.io/ubi9/go-toolset:1.24@sha256:6fd64cd7f38a9b87440f963b6c04953d04de65c35b9672dbd7f1805b0ae20d09
  params:
    - name: repository
      type: string
      description: Volume with resources to be applied.
    - name: operator-component
      type: string
      description: Operator component used (operator, operator-bundle, ...).
    - name: git-url
      type: string
      description: Operator repository url.
    - name: git-revision
      type: string
      description: Operator repository revision.
  volumeMounts:
    - name: "$(params.repository)"
      mountPath: /repository
  env:
    - name: OPERATOR_COMPONENT
      value: "$(params.operator-component)"
    - name: GIT_URL
      value: "$(params.git-url)"
    - name: GIT_REVISION
      value: "$(params.git-revision)"
  script: |
    cd /repository
    if [[ "$OPERATOR_COMPONENT" == "rhtas-operator" || "$OPERATOR_COMPONENT" == "rhtas-operator-bundle" ]]; then
      echo "Cloning from $GIT_URL"
      git clone $GIT_URL source
      cd source
      git checkout $GIT_REVISION
    else
      echo "Cloning from default url"
      git clone "https://github.com/securesign/secure-sign-operator.git" source
      cd source
    fi
