apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: prepare-mvo-environment
spec:
  description: >-
    This StepAction prepares the environment for MVO.
  image: registry.redhat.io/openshift4/ose-cli
  params:
    - name: credentials
      type: string
      description: Name of the volume with credentials.
    - name: repository
      type: string
      description: Volume with resources to be applied.
    - name: workdir
      type: string
      description: Repository home directory.
    - name: KUBECONFIG
      type: string
      description: KUBECONFIG path.
    - name: mvo-namespace
      description: Namespace in which the MVO is created.
      type: string
    - name: mvo-e2e-namespace
      description: Namespace in which the MVO E2E Tests run.
      type: string
    - name: model-test-image
      description: Model Test Image.
      type: string
  volumeMounts:
    - name: "$(params.credentials)"
      mountPath: /credentials
    - name: "$(params.repository)"
      mountPath: /repository
  env:
    - name: KUBECONFIG
      value: "/credentials/$(params.KUBECONFIG)"
    - name: MVO_NAMESPACE
      value: "$(params.mvo-namespace)"
    - name: MVO_E2E_NAMESPACE
      value: "$(params.mvo-e2e-namespace)"
    - name: WORKDIR
      value: "$(params.workdir)"
    - name: MODEL_TEST_IMAGE
      value: "$(params.model-test-image)"
  script: |
    cd /repository/$WORKDIR/test/e2e/testdata/
    oc get ns "$MVO_NAMESPACE" >/dev/null 2>&1 || oc create ns "$MVO_NAMESPACE"
    oc get ns "$MVO_E2E_NAMESPACE" >/dev/null 2>&1 || oc create ns "$MVO_E2E_NAMESPACE"

    sed -i -E "s|(^[[:space:]]*image:[[:space:]]*).*|\1${MODEL_TEST_IMAGE}|" model-data-daemonset.yaml

    oc apply -n "$MVO_E2E_NAMESPACE" model-data-daemonset.yaml