apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Konflux components
  - konflux/base
  - pipelines/base
  # RHTAS components
  - model-transparency-go/base
  - rhtas-console/base
