apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1-1

resources:
  - ../../base/fbc
  - ../../base/operator

patches:
  - path: patch.yaml
    target:
      name: operator
      kind: ProjectDevelopmentStream
  - path: fbc-patch.yaml
    target:
      name: fbc-v4-14
      kind: ProjectDevelopmentStream
  - path: fbc-patch.yaml
    target:
      name: fbc-v4-15
      kind: ProjectDevelopmentStream
  - path: fbc-patch.yaml
    target:
      name: fbc-v4-16
      kind: ProjectDevelopmentStream
  - path: fbc-patch.yaml
    target:
      name: fbc-v4-17
      kind: ProjectDevelopmentStream
  - path: fbc-patch.yaml
    target:
      name: fbc-v4-18
      kind: ProjectDevelopmentStream
