apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - template.yaml

components:
  - ../../base/ec

patches:
  - target:
      name: cli-stacks-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/gitsign-cli-stack.yaml
  - target:
      name: cli-stacks-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/cosign-cli-stack.yaml
  - target:
      name: cli-stacks-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/rekor-cli-stack.yaml
  - target:
      name: cli-stacks-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/trillian-cli-stack.yaml
  - target:
      name: cli-stacks-template
      kind: ProjectDevelopmentStreamTemplate
    path: patch/fetch-tsa-certs-cli-stack.yaml
