apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository 
metadata:
  name: imagerepository-for-timestamp-authority-timestamp-authority
  labels:
    appstudio.redhat.com/component: timestamp-authority
spec:
  image:
    name: rhtas-tenant/timestamp-authority/timestamp-authority
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
