apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/pipelines?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && 
      ( ".tekton/docker-build-push.yaml".pathChanged() || "pipeline-tests".pathChanged() || "pipelines/docker-build.yaml".pathChanged() || "tasks/go-unit-test.yaml".pathChanged() )
    pipelinesascode.tekton.dev/pipeline: "pipelines/docker-build.yaml"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pipelines
    appstudio.openshift.io/component: docker-build
    pipelines.appstudio.openshift.io/type: build
  name: docker-build-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtas-tenant/docker-build:{{revision}}
  - name: dockerfile
    value: pipeline-tests/Dockerfile
  - name: build-source-image
    value: true
  - name: prefetch-input
    value: '{"path": "pipeline-tests", "type": "gomod"}'
  - name: hermetic
    value: true
  - name: go_unit_test
    value: true
  - name: go_test_command
    value: cd pipeline-tests && go test ./...
  pipelineRef:
    name: docker-build
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
