apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/pipelines?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( ".tekton/docker-build-multi-platform-oci-ta-push.yaml".pathChanged()
      || "pipeline-tests".pathChanged() || "pipelines/docker-build-multi-platform-oci-ta.yaml".pathChanged()
      )
    pipelinesascode.tekton.dev/pipeline: pipelines/docker-build-multi-platform-oci-ta.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pipelines
    appstudio.openshift.io/component: docker-build-multi-platform-oci-ta
    pipelines.appstudio.openshift.io/type: build
  name: docker-build-multi-platform-oci-ta-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtas-tenant/docker-build-multi-platform-oci-ta:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: pipeline-tests/Dockerfile
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '{"path": "pipeline-tests", "type": "gomod"}'
  - name: hermetic
    value: "true"
  pipelineRef:
    name: docker-build-multi-platform-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-docker-build-multi-platform-oci-ta
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
