apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/pipelines?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && ( ".tekton/docker-build-oci-ta-pull-request.yaml".pathChanged()
      || "pipeline-tests".pathChanged() || "pipelines/docker-build-oci-ta.yaml".pathChanged()
      || "tasks/go-unit-test-oci-ta.yaml".pathChanged() )
    pipelinesascode.tekton.dev/pipeline: pipelines/docker-build-oci-ta.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pipelines
    appstudio.openshift.io/component: docker-build-oci-ta
    pipelines.appstudio.openshift.io/type: build
  name: docker-build-oci-ta-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtas-tenant/docker-build-oci-ta:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: pipeline-tests/Dockerfile
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '{"path": "pipeline-tests", "type": "gomod"}'
  - name: hermetic
    value: "true"
  - name: go_unit_test
    value: "true"
  - name: go_test_command
    value: cd pipeline-tests && go test ./...
  pipelineRef:
    name: docker-build-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-docker-build-oci-ta
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
