apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/pipelines?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "pipeline-tests/fbc/***".pathChanged() || ".tekton/fbc-builder-push.yaml".pathChanged()
      || "pipeline-tests/fbc/catalog.Dockerfile".pathChanged() || "pipelines/fbc-builder.yaml".pathChanged()
      )
    pipelinesascode.tekton.dev/pipeline: pipelines/fbc-builder.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pipelines
    appstudio.openshift.io/component: fbc-builder
    pipelines.appstudio.openshift.io/type: build
  name: fbc-builder-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtas-tenant/fbc-builder:{{revision}}
  - name: dockerfile
    value: pipeline-tests/fbc/catalog.Dockerfile
  - name: path-context
    value: pipeline-tests/fbc
  pipelineRef:
    name: fbc-builder
  taskRunTemplate:
    serviceAccountName: build-pipeline-fbc-builder
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
