---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhtas-build-bot
  namespace: rhtas-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhtas-build-bot-role
  namespace: rhtas-tenant
rules:
  - apiGroups: ["appstudio.redhat.com"]
    resources: ["releases", "releaseplans", "snapshots"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhtas-build-bot-rolebinding
  namespace: rhtas-tenant
subjects:
  - kind: ServiceAccount
    name: rhtas-build-bot
    namespace: rhtas-tenant
roleRef:
  kind: Role
  name: rhtas-build-bot-role
  apiGroup: rbac.authorization.k8s.io
---
