apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: install-tas-from-repository
spec:
  description: >-
    This StepAction install trusted artifact signer.
  image: registry.redhat.io/openshift4/ose-cli
  params:
    - name: credentials
      type: string
      description: Name of the volume with credentials.
    - name: workdir
      type: string
      description: Repository home directory.
      default: ""
    - name: KUBECONFIG
      type: string
      description: KUBECONFIG path.
    - name: tas-namespace
      description: Namespace in which the TAS is created.
      type: string
    - name: OIDC_ISSUER_URL
      description: Trusted artifact signer issuer url
      type: string
  results:
    - name: fulcio-url
    - name: tuf-url
    - name: rekor-url
    - name: rekor-ui-url
    - name: tsa-url
  volumeMounts:
    - name: "$(params.credentials)"
      mountPath: /credentials
  env:
    - name: KUBECONFIG
      value: "/credentials/$(params.KUBECONFIG)"
    - name: WORKDIR
      value: "$(params.workdir)"
    - name: TASNAMESPACE
      value: "$(params.tas-namespace)"
    - name: OIDC_ISSUER_URL
      value: "$(params.OIDC_ISSUER_URL)"
  script: |
    cd $WORKDIR
    sed -i "s#https://your-oidc-issuer-url#$OIDC_ISSUER_URL#" config/samples/rhtas_v1alpha1_securesign.yaml
    sed -i 's#rhtas.redhat.com/metrics: "true"#rhtas.redhat.com/metrics: "false"#' config/samples/rhtas_v1alpha1_securesign.yaml
    oc create ns $TASNAMESPACE || true
    oc create -f config/samples/rhtas_v1alpha1_securesign.yaml -n $TASNAMESPACE
    sleep 1
    oc wait --for=condition=Ready securesign/securesign-sample --timeout=9m -n $TASNAMESPACE
    
    oc get fulcio -o jsonpath='{.items[0].status.url}' -n $TASNAMESPACE > "$(step.results.fulcio-url.path)"
    oc get tuf -o jsonpath='{.items[0].status.url}' -n $TASNAMESPACE > "$(step.results.tuf-url.path)"
    oc get rekor -o jsonpath='{.items[0].status.url}' -n $TASNAMESPACE > "$(step.results.rekor-url.path)"
    oc get rekor -o jsonpath='{.items[0].status.rekorSearchUIUrl}' -n $TASNAMESPACE > "$(step.results.rekor-ui-url.path)"
    oc get timestampauthority -o jsonpath='{.items[0].status.url}' -n $TASNAMESPACE > "$(step.results.tsa-url.path)"
