apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: install-keycloak-from-repository
spec:
  description: >-
    This StepAction installs and configures a Keycloak instance on either OpenShift or kind clusters.
  image: registry.redhat.io/openshift4/ose-cli
  params:
    - name: credentials
      type: string
      description: Name of the volume with credentials.
    - name: workdir
      type: string
      description: Repository home directory.
      default: ""
    - name: KUBECONFIG
      type: string
      description: KUBECONFIG path.
    - name: cluster-platform
      type: string
      default: "openshift"
      description: "Target environment for Keycloak installation: openshift or kind"
  results:
    - name: oidc-hostname
      description: Hostname of the installed OIDC provider
    - name: oidc-issuer-url
      description: Trusted artifact signer issuer url
  volumeMounts:
    - name: "$(params.credentials)"
      mountPath: /credentials
  env:
    - name: KUBECONFIG
      value: "/credentials/$(params.KUBECONFIG)"
    - name: WORKDIR
      value: "$(params.workdir)"
    - name: CLUSTER_PLATFORM
      value: "$(params.cluster-platform)"
  script: |
    cd $WORKDIR

    if [[ "$CLUSTER_PLATFORM" == "kind" ]]; then
      ci/openshift/tas-keycloak-install.sh kind
    else
      ci/openshift/tas-keycloak-install.sh
    fi

    OIDC_HOSTNAME=$(oc get route -n keycloak-system -l app=keycloak -o jsonpath='{.items[0].status.ingress[0].host}')
    OIDC_ISSUER_URL="https://$OIDC_HOSTNAME/realms/trusted-artifact-signer"

    printf %s "$OIDC_HOSTNAME" > "$(step.results.oidc-hostname.path)"
    printf %s "$OIDC_ISSUER_URL" > "$(step.results.oidc-issuer-url.path)"
