apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: install-keycloak-from-repository
spec:
  description: >-
    This StepAction install RHSSO operator and create Keycloak instance using predefined script.
  image: registry.redhat.io/openshift4/ose-cli
  params:
    - name: credentials
      type: string
      description: Name of the volume with credentials.
    - name: workdir
      type: string
      description: Repository home directory.
      default: ""
    - name: KUBECONFIG
      type: string
      description: KUBECONFIG path.
    - name: keycloak-distribution
      type: string
      default: "rhsso"
      description: "Which Keycloak build to install rhsso or rhbk"
  results:
    - name: oidc-hostname
      description: Hostname of the installed OIDC provider
    - name: oidc-issuer-url
      description: Trusted artifact signer issuer url
  volumeMounts:
    - name: "$(params.credentials)"
      mountPath: /credentials
  env:
    - name: KUBECONFIG
      value: "/credentials/$(params.KUBECONFIG)"
    - name: WORKDIR
      value: "$(params.workdir)"
    - name: KEYCLOAK_DISTRIBUTION
      value: "$(params.keycloak-distribution)"
  script: |
    cd $WORKDIR

    if [[ "$KEYCLOAK_DISTRIBUTION" == "rhbk" ]]; then
      ci/openshift/tas-keycloak-install.sh rhbk
      OIDC_HOSTNAME=$(oc get route -n keycloak-system -l app=keycloak -o jsonpath='{.items[0].status.ingress[0].host}')
      OIDC_ISSUER_URL="https://$OIDC_HOSTNAME/realms/trusted-artifact-signer"
    else
      ci/openshift/tas-keycloak-install.sh
      OIDC_HOSTNAME=$(oc get route -n keycloak-system keycloak -o jsonpath='{.status.ingress[0].host}')
      OIDC_ISSUER_URL="https://$OIDC_HOSTNAME/auth/realms/trusted-artifact-signer"
    fi

    printf %s "$OIDC_HOSTNAME" > "$(step.results.oidc-hostname.path)"
    printf %s "$OIDC_ISSUER_URL" > "$(step.results.oidc-issuer-url.path)"
