apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tturek-tenant

resources:
  - ../../base/project
  - ../../base/stream
  - ../../base/serviceAccounts
  - ../../base/releasePlans
  - ../../base/application

configMapGenerator:
  - name: registry-config
    literals:
      - registry-namespace=osmman
      - github-org=osmman

replacements:
  - source:
      kind: ConfigMap
      name: registry-config
      fieldPath: data.registry-namespace
    targets:
      - select:
          kind: Component
        fieldPaths:
          - spec.containerImage
        options:
          delimiter: '/'
          index: 1
  - source:
      kind: ConfigMap
      name: registry-config
      fieldPath: data.github-org
    targets:
      - select:
          kind: Component
        fieldPaths:
          - spec.source.git.url
        options:
          delimiter: '/'
          index: 3
