apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhtas-dev-tenant

resources:
  - ../../base/service-account
  - ../../base/release-plan
  - ../../base/application
  - ../../base/project
  - ../../base/stream

configMapGenerator:
  - name: registry-config
    literals:
      - registry-namespace=rhtas-dev-tenant
      - github-org=securesign
      - mintmaker-disabled="true"

replacements:
  # Set mintmaker disabled annotation to "true" for all Components (standalone and in templates)
  - source:
      kind: ConfigMap
      name: registry-config
      fieldPath: data.mintmaker-disabled
    targets:
      - select:
          kind: Component
        fieldPaths:
          - metadata.annotations.[mintmaker.appstudio.redhat.com/disabled]
        options:
          create: true
      - select:
          kind: ProjectDevelopmentStreamTemplate
        fieldPaths:
          - spec.resources.[kind=Component].metadata.annotations.[mintmaker.appstudio.redhat.com/disabled]
        options:
          create: true
  - source:
      kind: ConfigMap
      name: registry-config
      fieldPath: data.registry-namespace
    targets:
      - select:
          kind: ImageRepository
        fieldPaths:
          - spec.image.name
        options:
          delimiter: '/'
          index: 0
  - source:
      kind: ConfigMap
      name: registry-config
      fieldPath: data.github-org
    targets:
      - select:
          kind: Component
        fieldPaths:
          - spec.source.git.url
        options:
          delimiter: '/'
          index: 3
