apiVersion: projctl.konflux.dev/v1beta1
kind: Project
metadata:
  name: rekor-monitor
spec:
  displayName: "Red Hat Trusted Artifact Signer Rekor Monitor"
  description: |
    Rekor transparency log monitoring