apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: rekor-monitor-template
  labels:
    build.rhtas.com/ec: registry-rhtas
    build.rhtas.com/type: component
spec:
  project: rekor-monitor
  variables:
    - name: version
      description: A version number for a new development stream
    - name: branch
      description: Git branch
      defaultValue: "main"
    - name: nameSuffix
      description: A suffix which will be added to K8s resource name
      defaultValue: "-{{hyphenize .version}}"
    - name: application
      description: The application name
      defaultValue: "rekor-monitor"
    - name: rekorMonitorComponent
      description: The rekor-monitor component name
      defaultValue: "rekor-monitor"
    - name: ctlogMonitorComponent
      description: The ctlog-monitor component name
      defaultValue: "ctlog-monitor"
    - name: mintmakerDisabled
      description: Whether to disable mintmaker annotation on the Component
      defaultValue: "false"
  resources:
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Application
      metadata:
        annotations:
          application.thumbnail: "5"
        name: "{{.application}}{{.nameSuffix}}"
      spec:
        displayName: "{{.application}} ({{.version}})"
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
          git-provider: github
          git-provider-url: https://github.com
          mintmaker.appstudio.redhat.com/disabled: "{{.mintmakerDisabled}}"
        name: "{{.rekorMonitorComponent}}{{.nameSuffix}}"
      spec:
        application: "{{.application}}{{.nameSuffix}}"
        componentName: "{{.rekorMonitorComponent}}"
        source:
          git:
            url: https://github.com/securesign/rekor-monitor
            revision: "{{.branch}}"
            dockerfileUrl: Dockerfile.rekor-monitor.rh
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
          git-provider: github
          git-provider-url: https://github.com
          mintmaker.appstudio.redhat.com/disabled: "{{.mintmakerDisabled}}"
        name: "{{.ctlogMonitorComponent}}{{.nameSuffix}}"
      spec:
        application: "{{.application}}{{.nameSuffix}}"
        componentName: "{{.ctlogMonitorComponent}}"
        source:
          git:
            url: https://github.com/securesign/rekor-monitor
            revision: "{{.branch}}"
            dockerfileUrl: Dockerfile.ctlog-monitor.rh
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: ImageRepository 
      metadata:
        name: "imagerepository-for-{{.application}}{{.nameSuffix}}-{{.rekorMonitorComponent}}"
        labels:
          appstudio.redhat.com/component: "{{.rekorMonitorComponent}}{{.nameSuffix}}"
      spec:
        image:
          name: rhtas-tenant/rekor-monitor
          visibility: public
        notifications:
          - config:
              url: https://bombino.api.redhat.com/v1/sbom/quay/push
            event: repo_push
            method: webhook
            title: SBOM-event-to-Bombino
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: ImageRepository 
      metadata:
        name: "imagerepository-for-{{.application}}{{.nameSuffix}}-{{.ctlogMonitorComponent}}"
        labels:
          appstudio.redhat.com/component: "{{.ctlogMonitorComponent}}{{.nameSuffix}}"
      spec:
        image:
          name: rhtas-tenant/ctlog-monitor
          visibility: public
        notifications:
          - config:
              url: https://bombino.api.redhat.com/v1/sbom/quay/push
            event: repo_push
            method: webhook
            title: SBOM-event-to-Bombino
