---

apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository 
metadata:
  name: rhtas-console
  labels:
    appstudio.redhat.com/component: rhtas-console
spec:
  image:
    name: rhtas-tenant/rhtas-console
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---

apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository 
metadata:
  name: rhtas-console-ui
  labels:
    appstudio.redhat.com/component: rhtas-console-ui
spec:
  image:
    name: rhtas-tenant/rhtas-console-ui
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino

---
