apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: model-validation-operator
spec:
  project: model-validation-operator
  template:
    name: model-validation-operator-template
    values:
      - name: version
        value: "main"
      - name: branch
        value: "main"
      - name: nameSuffix
        value: ""
